-- Compiled (executed) checks for Section V of Bian & Feng, i.e. for
-- Kopt.Descent and Kopt.Optimality.
--
-- (A) The hypothesis CliffordK2 of Kopt.Optimality: every two-qubit
--     Clifford operator is implementable with at most two K gates.
--     This is verified exhaustively, as follows. Let
--
--       S₀ = the group generated by the gates of 𝒢 other than K₀, K₁
--            and CS (the generalized permutations),
--       S₁ = the closure of K₀·S₀ ∪ K₁·S₀ under left multiplication
--            by those generators, together with S₀,
--       S₂ = the same construction one step further.
--
--     Every element of S₂ is, by construction, a product of at most
--     two K gates and generalized permutations. The program computes
--     S₂ and then checks that S₂ is closed under left multiplication
--     by *every* Clifford generator, including K₀ and K₁. Since
--     1 ∈ S₂, that makes S₂ the whole two-qubit Clifford group, and
--     so every Clifford operator has K-count at most 2.
--
-- (B) The bounds of Section V on the authors' data set, and (C) the
--     residue-level enumeration behind Lemma V.6.
--     (Kopt/Haskell/experiment_data.dat, 12000 records
--     ((l, γˡU), ourCS, glaudellCS, ourK, glaudellK)). Glaudell et
--     al.'s algorithm is CS-optimal, so glaudellCS is cs(U), and by
--     Corollary V.8 ourK is kc(U). With k = ourK and s = glaudellCS
--     we check
--
--       Theorem V.9   : k ≤ 2s+2  and  s ≤ k+1,
--       Corollary V.10: (k+1)(k-2) ≤ (2(k-2)+6)·s  (the CORRECTED
--                       constant; the count of records for which the
--                       published constant 4 fails is reported),
--       Remark V.11   : l-2 ≤ s ≤ 2l+1,
--       Corollary V.8 : csc (synth U) ≤ kc+1 and rlen ≤ 10·kc+9,
--     and, on a sample, that ourCS and ourK really are the counts of
--     the circuit synth produces.
--
-- (D) The four residue-level enumerations that Kopt.NormalForms runs at
--     type-check time, re-evaluated here, together with a cross-check
--     of the cheap pattern invariant used there against the orbit
--     search pat-of-z2 used in (C).
--
-- Usage: agda-run.sh Test/KoptOptimalityRun.agda [DATAFILE] [SAMPLE]
-- SAMPLE limits the number of records on which synth is run (the
-- arithmetic checks always use every record); the default is 500.
--

{-# OPTIONS --guardedness #-}

module Test.KoptOptimalityRun where

open import IO
open import System.Environment using (getArgs)

open import Data.Bool.Base using (Bool ; true ; false ; if_then_else_ ; _∧_ ; _∨_ ; not)
open import Data.Char.Base as Char using (Char)
open import Data.List.Base as List using (List ; [] ; _∷_ ; _++_)
open import Data.Maybe.Base using (Maybe ; just ; nothing)
open import Data.Nat.Base as Nat using (ℕ ; zero ; suc ; _∸_)
import Data.Nat.Properties as NatP
open import Data.Integer.Base as Int using (ℤ ; +_)
open import Data.Product.Base using (_×_ ; _,_ ; proj₁ ; proj₂)
open import Data.String.Base as Str using (String)
open import Data.Vec.Base as Vec using (Vec ; [] ; _∷_)
import Data.Unit.Polymorphic.Base as PU
open import Level using (0ℓ)

import Data.Tree.AVL.Sets

open import Instances
open import Literals
open import Quantum.Synthesis.Ring
open import Quantum.Synthesis.Matrix
open import Kopt.Base
open import Kopt.Gates
open import Kopt.Permutations
open import Kopt.Patterns
open import Kopt.Synth
import Kopt.NormalForms as NF

-- Sets of natural numbers, used to recognise matrices that have
-- already been seen.
module KeySet = Data.Tree.AVL.Sets NatP.<-strictTotalOrder

Op : Set
Op = Matrix 4 4 DComplex

-- ----------------------------------------------------------------------
-- * (A) The two-qubit Clifford group

-- A key that identifies a Clifford operator. Every Clifford operator
-- has lde at most 2 (Remark II.2), so γ²·C is a matrix over ℤ[i]
-- whose entries have norm at most 4, i.e. real and imaginary parts
-- between -2 and 2. Encoding each part in a digit of base 64 (with
-- an offset of 32) is therefore injective.
private
  entry-key : ZComplex -> ℕ
  entry-key (Cplx a b) = Int.∣ a Int.+ (+ 32) ∣ Nat.* 64 Nat.+ Int.∣ b Int.+ (+ 32) ∣

  key-of-entries : ℕ -> List ZComplex -> ℕ
  key-of-entries acc [] = acc
  key-of-entries acc (x ∷ xs) = key-of-entries (acc Nat.* 4096 Nat.+ entry-key x) xs

mat-key : Op -> ℕ
mat-key m = key-of-entries 0 (matrix-entries (integral-matrix 2 m))

-- The gates that generate the generalized permutations, and all the
-- Clifford generators (the gate set 𝒢 without CS).
gp-gens clifford-gens : List Gate
gp-gens = X₀ ∷ X₁ ∷ Z₀ ∷ Z₁ ∷ S₀ ∷ S₁ ∷ CZ ∷ CX ∷ XC ∷ Ex ∷ Ii ∷ []
clifford-gens = K₀ ∷ K₁ ∷ gp-gens

private
  Acc : Set
  Acc = KeySet.⟨Set⟩ × List Op

  -- Add a matrix to the accumulator if it is new.
  add-key : Acc -> Op -> ℕ -> Acc
  add-key (vis , new) m k =
    if KeySet.member k vis then (vis , new) else (KeySet.insert k vis , m ∷ new)

  add : Acc -> Op -> Acc
  add st m = add-key st m (mat-key m)

  -- All images of m under the given gates.
  images : List Gate -> Op -> List Op
  images gs m = List.map (λ g -> ⟦ g ⟧g * m) gs

  add-all : Acc -> List Op -> Acc
  add-all st [] = st
  add-all st (m ∷ ms) = add-all (add st m) ms

  expand-level : List Gate -> Acc -> List Op -> Acc
  expand-level gs st [] = st
  expand-level gs st (m ∷ ms) = expand-level gs (add-all st (images gs m)) ms

  -- Breadth-first closure under left multiplication by the gates gs.
  -- The first argument is fuel: one unit per level.
  close : ℕ -> List Gate -> KeySet.⟨Set⟩ -> List Op -> List Op -> KeySet.⟨Set⟩ × List Op
  close-step : ℕ -> List Gate -> List Op -> Acc -> KeySet.⟨Set⟩ × List Op

  close zero gs vis acc frontier = vis , acc
  close (suc n) gs vis acc [] = vis , acc
  close (suc n) gs vis acc frontier@(_ ∷ _) =
    close-step n gs acc (expand-level gs (vis , []) frontier)

  close-step n gs acc (vis , new) = close n gs vis (new ++ acc) new

  -- One K-level: multiply everything by K₀ and by K₁ and close again.
  k-level : ℕ -> KeySet.⟨Set⟩ -> List Op -> List Op -> KeySet.⟨Set⟩ × List Op
  k-level fuel vis acc level =
    k-level-step fuel acc (add-all (vis , []) (List.concatMap (images (K₀ ∷ K₁ ∷ [])) level))
    where
      k-level-step : ℕ -> List Op -> Acc -> KeySet.⟨Set⟩ × List Op
      k-level-step f a (vis' , new) = close f gp-gens vis' (new ++ a) new

  -- Is every image of every element of the list already known?
  closed? : KeySet.⟨Set⟩ -> List Op -> Bool
  closed-one? : KeySet.⟨Set⟩ -> List Op -> Bool

  closed? vis [] = true
  closed? vis (m ∷ ms) = if closed-one? vis (images clifford-gens m) then closed? vis ms else false

  closed-one? vis [] = true
  closed-one? vis (m ∷ ms) = if KeySet.member (mat-key m) vis then closed-one? vis ms else false

-- The three levels. The fuel (100 levels of breadth-first search) is
-- never exhausted: the Clifford group is finite and the search stops
-- as soon as a level is empty.
private
  level0 : KeySet.⟨Set⟩ × List Op
  level0 = close 100 gp-gens (KeySet.insert (mat-key 1#) KeySet.empty) (1# ∷ []) (1# ∷ [])

  level1 : KeySet.⟨Set⟩ × List Op
  level1 = k-level 100 (proj₁ level0) (proj₂ level0) (proj₂ level0)

  level2 : KeySet.⟨Set⟩ × List Op
  level2 = k-level 100 (proj₁ level1) (proj₂ level1) (proj₂ level1)

-- ----------------------------------------------------------------------
-- * (B) A scanner for the data file

private
  digit-val : Char -> ℕ
  digit-val c = Char.toℕ c ∸ 48

  read-nat : ℕ -> List Char -> ℕ × List Char
  read-nat a [] = a , []
  read-nat a (c ∷ cs) =
    if Char.isDigit c then read-nat (a Nat.* 10 Nat.+ digit-val c) cs else (a , c ∷ cs)

  line-ints : ℕ -> List Char -> List ℤ
  emit-pos emit-neg : ℕ -> ℕ × List Char -> List ℤ

  line-ints zero cs = []
  line-ints (suc n) [] = []
  line-ints (suc n) (c ∷ cs) with Char.isDigit c
  ... | true = emit-pos n (read-nat (digit-val c) cs)
  ... | false with c Char.≈ᵇ '-'
  ...   | false = line-ints n cs
  ...   | true with cs
  ...     | [] = []
  ...     | (d ∷ ds) with Char.isDigit d
  ...       | false = line-ints n cs
  ...       | true = emit-neg n (read-nat (digit-val d) ds)

  emit-pos n (v , rest) = (+ v) ∷ line-ints n rest
  emit-neg n (v , rest) = Int.- (+ v) ∷ line-ints n rest

  ints-of-string : String -> List ℤ
  ints-of-string s = ints-of-chars (Str.toList s)
    where
      ints-of-chars : List Char -> List ℤ
      ints-of-chars cs = line-ints (List.length cs) cs

  nat-of-string : String -> ℕ
  nat-of-string s = proj₁ (read-nat 0 (Str.toList s))

  record Record : Set where
    constructor record'
    field
      rec-lde : ℕ
      rec-mat : Matrix 4 4 ZComplex
      rec-cs rec-gcs rec-k rec-gk : ℕ
  open Record

  parse-record : List ℤ -> Maybe Record
  parse-record ( l
               ∷ a₀ ∷ b₀ ∷ a₁ ∷ b₁ ∷ a₂ ∷ b₂ ∷ a₃ ∷ b₃
               ∷ c₀ ∷ d₀ ∷ c₁ ∷ d₁ ∷ c₂ ∷ d₂ ∷ c₃ ∷ d₃
               ∷ e₀ ∷ f₀ ∷ e₁ ∷ f₁ ∷ e₂ ∷ f₂ ∷ e₃ ∷ f₃
               ∷ g₀ ∷ h₀ ∷ g₁ ∷ h₁ ∷ g₂ ∷ h₂ ∷ g₃ ∷ h₃
               ∷ ourcs ∷ jcs ∷ ourk ∷ jk ∷ []) =
    just (record' Int.∣ l ∣
                  (matrix4x4 (Cplx a₀ b₀ , Cplx a₁ b₁ , Cplx a₂ b₂ , Cplx a₃ b₃)
                             (Cplx c₀ d₀ , Cplx c₁ d₁ , Cplx c₂ d₂ , Cplx c₃ d₃)
                             (Cplx e₀ f₀ , Cplx e₁ f₁ , Cplx e₂ f₂ , Cplx e₃ f₃)
                             (Cplx g₀ h₀ , Cplx g₁ h₁ , Cplx g₂ h₂ , Cplx g₃ h₃))
                  Int.∣ ourcs ∣ Int.∣ jcs ∣ Int.∣ ourk ∣ Int.∣ jk ∣)
  parse-record _ = nothing

  scale-from-whole : DComplex -> ZComplex -> DComplex
  scale-from-whole g z = from-whole z * g

  operator-of : Record -> Op
  operator-of r = matrix-map (scale-from-whole ((1/γ) ^ rec-lde r)) (rec-mat r)

-- ----------------------------------------------------------------------
-- ** The checks of Section V on one record

private
  -- The arithmetic checks, which use only the recorded counts.
  -- k = ourK = kc(U) (Corollary V.8), s = glaudellCS = cs(U).
  record Arith : Set where
    constructor arith
    field
      a-v9lo a-v9hi a-v10 a-v11lo a-v11hi a-paper : Bool
  open Arith

  arith-of : Record -> Arith
  arith-of r = arith
    (k Nat.≤ᵇ (2 Nat.* s Nat.+ 2))
    (s Nat.≤ᵇ suc k)
    ((suc k Nat.* (k ∸ 2)) Nat.≤ᵇ ((2 Nat.* (k ∸ 2) Nat.+ 6) Nat.* s))
    ((l ∸ 2) Nat.≤ᵇ s)
    (s Nat.≤ᵇ suc (2 Nat.* l))
    ((suc k Nat.* (k ∸ 2)) Nat.≤ᵇ ((2 Nat.* (k ∸ 2) Nat.+ 4) Nat.* s))
    where
      l = rec-lde r
      s = rec-gcs r
      k = rec-k r

  -- The checks that run synth.
  record Synthc : Set where
    constructor synthc
    field
      s-lde s-exact s-k s-cs s-bounds : Bool
  open Synthc

  synth-with : Record -> Op -> Circuit -> Synthc
  synth-with r u c = synthc
    (lde u Nat.≡ᵇ rec-lde r)
    (⟦ c ⟧ == u)
    (kc c Nat.≡ᵇ rec-k r)
    (csc c Nat.≡ᵇ rec-cs r)
    ((csc c Nat.≤ᵇ suc (kc c)) ∧ (rlen c Nat.≤ᵇ (10 Nat.* kc c Nat.+ 9)))

  synth-of-op : Record -> Op -> Synthc
  synth-of-op r u = synth-with r u (synth u)

  synth-of-record : Record -> Synthc
  synth-of-record r = synth-of-op r (operator-of r)

-- ----------------------------------------------------------------------
-- ** Accumulating

private
  record Acc2 : Set where
    constructor acc2
    field
      n-total : ℕ
      n-v9lo n-v9hi n-v10 n-v11lo n-v11hi n-paper : ℕ
      n-syn : ℕ
      n-lde n-exact n-k n-cs n-bounds : ℕ
  open Acc2

  acc0 : Acc2
  acc0 = acc2 0 0 0 0 0 0 0 0 0 0 0 0 0

  bump : Bool -> ℕ -> ℕ
  bump true k = k
  bump false k = suc k

  add-arith : Acc2 -> Arith -> Acc2
  add-arith (acc2 t a b c d e f sy p q r s u) (arith a' b' c' d' e' f') =
    acc2 (suc t) (bump a' a) (bump b' b) (bump c' c) (bump d' d) (bump e' e)
         (bump f' f) sy p q r s u

  add-synth : Acc2 -> Synthc -> Acc2
  add-synth (acc2 t a b c d e f sy p q r s u) (synthc p' q' r' s' u') =
    acc2 t a b c d e f (suc sy) (bump p' p) (bump q' q) (bump r' r) (bump s' s) (bump u' u)

  acc-sum : Acc2 -> ℕ
  acc-sum (acc2 t a b c d e f sy p q r s u) =
    t Nat.+ a Nat.+ b Nat.+ c Nat.+ d Nat.+ e Nat.+ f Nat.+ sy Nat.+ p Nat.+ q Nat.+ r Nat.+ s Nat.+ u

  force-io : ℕ -> IO {0ℓ} PU.⊤
  force-io zero = pure _
  force-io (suc n) = pure _

  -- The main loop: the arithmetic checks on every record, the synth
  -- checks on the first "sample" records.
  loop : ℕ -> ℕ -> Acc2 -> List String -> IO Acc2
  loop-line : ℕ -> ℕ -> Acc2 -> List String -> Maybe Record -> IO Acc2
  loop-rec : ℕ -> ℕ -> Acc2 -> List String -> Record -> IO Acc2
  loop-next : ℕ -> ℕ -> List String -> Acc2 -> IO Acc2

  loop cd sample a [] = pure a
  loop cd sample a (s ∷ ss) = loop-line cd sample a ss (parse-record (ints-of-string s))

  loop-line cd sample a ss nothing = loop cd sample a ss
  loop-line cd sample a ss (just r) = loop-rec cd sample a ss r

  loop-rec cd zero a ss r = loop-next cd 0 ss (add-arith a (arith-of r))
  loop-rec cd (suc sample) a ss r =
    loop-next cd sample ss (add-synth (add-arith a (arith-of r)) (synth-of-record r))

  loop-next zero sample ss a =
    putStrLn ("... " Str.++ show (n-total a) Str.++ " records") >> loop 499 sample a ss
  loop-next (suc cd) sample ss a = force-io (acc-sum a) >> loop cd sample a ss

-- ----------------------------------------------------------------------
-- * Reporting

private
  report : String -> ℕ -> ℕ -> String
  report name bad total =
    (if bad Nat.≡ᵇ 0 then "PASS " else "FAIL ") Str.++
    show (total ∸ bad) Str.++ "/" Str.++ show total Str.++ "  " Str.++ name

  report-bool : String -> Bool -> String
  report-bool name b = (if b then "PASS  " else "FAIL  ") Str.++ name

  print-acc : Acc2 -> List String
  print-acc (acc2 t a b c d e f sy p q r s u) =
      ("records: " Str.++ show t Str.++ ", of which " Str.++ show sy Str.++ " with synth")
    ∷ report "Thm V.9 lower: kc <= 2 cs + 2" a t
    ∷ report "Thm V.9 upper: cs <= kc + 1" b t
    ∷ report "Cor V.10 (corrected): (k+1)(k-2) <= (2(k-2)+6) cs" c t
    ∷ report "Remark V.11 lower: l-2 <= cs" d t
    ∷ report "Remark V.11 upper: cs <= 2l+1" e t
    ∷ ("INFO  the published Cor V.10 constant 4 fails on "
         Str.++ show f Str.++ "/" Str.++ show t Str.++ " records")
    ∷ report "lde U = recorded lde" p sy
    ∷ report "semantics of synth U = U (exact)" q sy
    ∷ report "kc (synth U) = recorded K-count" r sy
    ∷ report "csc (synth U) = recorded CS-count" s sy
    ∷ report "Cor V.8: csc <= kc+1 and rlen <= 10 kc + 9" u sy
    ∷ []


-- ----------------------------------------------------------------------
-- * (C) Lemma V.6, at the level of the residues
--
-- A K₁ gate on the left combines the rows 0,1 and the rows 2,3 of the
-- operator. The step is a 0-descent exactly when no pair is "mixed"
-- (one entry odd, the other even, which raises the lde) and the two
-- pairs are not both equal modulo γ² (which lowers it). In that case
-- the K action of Section II C,
--
--    1b₀b₁ / 1b′₀b′₁ ↦ [(b₀⊕b′₀)(b₁⊕b′₁⊕1), (b₀⊕b′₀)(b₁⊕b′₁)],
--    0b₀b₁ / 0b′₀b′₁ ↦ both (b₀⊕b′₀)(b₁⊕b′₁),
--
-- gives both entries of a K-pair the same parity b₀⊕b′₀, which is the
-- sum of the *second* digits of the two ρˡ₂ entries. So ρˡ₁ of the
-- target of a 0-descent is determined by ρˡ₂ of the source.
--
-- A general K-count-1 0-descent is L₂·K₁·L₁·A·R₁ (or the mirror
-- image); the outer generalized permutations L₂ and R₁ do not change
-- the pattern, and ρˡ₂(L₁·A·R) is ρ₂(L₁) times the normal form of
-- Section IV B times a column permutation and rescaling, which again
-- does not change the pattern. So it is enough to enumerate the
-- 24·16 = 384 residue classes of ρ₂(L₁) over the normal forms.
--
-- Lemma V.6 says that from pattern (vi) no such step reaches pattern
-- (ii) or pattern (v).

private
  fst-digit snd-digit : R2 -> Z2
  fst-digit (a ∷ b ∷ []) = a
  snd-digit (a ∷ b ∷ []) = b

  row-of : Matrix 4 4 R2 -> ℕ -> Vector 4 R2
  row-of m j = vsel4 (rows-4 m) j

  scale-row : R2 -> Vector 4 R2 -> Vector 4 R2
  scale-row c v = vector-map (c r2*_) v

  -- P·M for the left generalized permutation given by a row
  -- permutation and four unit phases.
  left-act : Tuple4 -> (R2 × R2 × R2 × R2) -> Matrix 4 4 R2 -> Matrix 4 4 R2
  left-act σ (c₀ , c₁ , c₂ , c₃) m =
    Matrix' (vector-transpose (scale-row c₀ (row-of m (sel σ 0)) ∷
                               scale-row c₁ (row-of m (sel σ 1)) ∷
                               scale-row c₂ (row-of m (sel σ 2)) ∷
                               scale-row c₃ (row-of m (sel σ 3)) ∷ []))

  and4 : Vector 4 Bool -> Bool
  and4 (a ∷ b ∷ c ∷ d ∷ []) = a ∧ b ∧ c ∧ d

  same-parity? : Vector 4 R2 -> Vector 4 R2 -> Bool
  same-parity? u v = and4 (vector-zipwith (λ x y -> fst-digit x == fst-digit y) u v)

  k-parity-row : Vector 4 R2 -> Vector 4 R2 -> Vector 4 Z2
  k-parity-row u v = vector-zipwith (λ x y -> snd-digit x + snd-digit y) u v

  -- The ρˡ₁ of the target of a K-count-1 step on the left, when that
  -- step is a 0-descent; nothing if it is not one.
  zero-descent-target : Matrix 4 4 R2 -> Maybe (Matrix 4 4 Z2)
  zero-descent-target m =
    zdt (row-of m 0) (row-of m 1) (row-of m 2) (row-of m 3)
    where
      zdt : Vector 4 R2 -> Vector 4 R2 -> Vector 4 R2 -> Vector 4 R2 -> Maybe (Matrix 4 4 Z2)
      zdt r0 r1 r2 r3 =
        if (same-parity? r0 r1 ∧ same-parity? r2 r3)
             ∧ not ((r0 == r1) ∧ (r2 == r3))
        then just (build (k-parity-row r0 r1) (k-parity-row r2 r3))
        else nothing
        where
          build : Vector 4 Z2 -> Vector 4 Z2 -> Matrix 4 4 Z2
          build p q = Matrix' (vector-transpose (p ∷ p ∷ q ∷ q ∷ []))

  -- The pattern of a 4×4 matrix over ℤ₂, up to row and column
  -- permutations (Lemma IV.1).
  or-else : Maybe SixCases -> Maybe SixCases -> Maybe SixCases
  or-else (just p) _ = just p
  or-else nothing q = q

  match-p : Matrix 4 4 Z2 -> List SixCases -> Maybe SixCases
  match-p m [] = nothing
  match-p m (p ∷ ps) = if m == pattern-matrix p then just p else match-p m ps

  match-y : Matrix 4 4 Z2 -> Tuple4 -> List Tuple4 -> Maybe SixCases
  match-y m x [] = nothing
  match-y m x (y ∷ ys) = or-else (match-p (permute-matrix x y m) six-cases) (match-y m x ys)

  match-x : Matrix 4 4 Z2 -> List Tuple4 -> Maybe SixCases
  match-x m [] = nothing
  match-x m (x ∷ xs) = or-else (match-y m x all-perms) (match-x m xs)

  pat-of-z2 : Matrix 4 4 Z2 -> Maybe SixCases
  pat-of-z2 m = match-x m all-perms

  bad-target? : Maybe SixCases -> Bool
  bad-target? (just II) = true
  bad-target? (just V) = true
  bad-target? _ = false

  -- The 16 phase vectors and the 384 residue classes of a left
  -- generalized permutation.
  r2-units : List R2
  r2-units = r2-one ∷ r2-i ∷ []

  unit4s : List (R2 × R2 × R2 × R2)
  unit4s = List.concatMap (λ a ->
             List.concatMap (λ b ->
               List.concatMap (λ c ->
                 List.map (λ d -> (a , b , c , d)) r2-units) r2-units) r2-units) r2-units

  left-classes : List (Tuple4 × (R2 × R2 × R2 × R2))
  left-classes = List.concatMap (λ σ -> List.map (λ cs -> (σ , cs)) unit4s) all-perms

  all-b : {A : Set} -> (A -> Bool) -> List A -> Bool
  all-b f [] = true
  all-b f (x ∷ xs) = if f x then all-b f xs else false

  v6-ok-one : Matrix 4 4 R2 -> Tuple4 × (R2 × R2 × R2 × R2) -> Bool
  v6-ok-one n lc = check (zero-descent-target (left-act (proj₁ lc) (proj₂ lc) n))
    where
      check : Maybe (Matrix 4 4 Z2) -> Bool
      check nothing = true
      check (just z) = not (bad-target? (pat-of-z2 z))

  v6-ok : Matrix 4 4 R2 -> Bool
  v6-ok n = all-b (v6-ok-one n) left-classes

  -- The normal forms of pattern (vi), and their transposes (for the
  -- mirror-image descents A·P·K₁).
  vi-forms : List (Matrix 4 4 R2)
  vi-forms = normal-forms VI 2 ++ List.map matrix-transpose (normal-forms VI 2)

  -- A sanity check of the classifier: the pattern of each pattern
  -- matrix is itself.
  pat-self? : SixCases -> Bool
  pat-self? p = same (pat-of-z2 (pattern-matrix p))
    where
      same : Maybe SixCases -> Bool
      same nothing = false
      same (just q) = q == p

  -- How many of the enumerated steps really are 0-descents, and which
  -- patterns they reach: without this the check above could be
  -- vacuous.
  zd-target-pat : Matrix 4 4 R2 -> Tuple4 × (R2 × R2 × R2 × R2) -> Maybe SixCases
  zd-target-pat n lc = go (zero-descent-target (left-act (proj₁ lc) (proj₂ lc) n))
    where
      go : Maybe (Matrix 4 4 Z2) -> Maybe SixCases
      go nothing = nothing
      go (just z) = pat-of-z2 z

  all-targets : List (Maybe SixCases)
  all-targets = List.concatMap (λ n -> List.map (zd-target-pat n) left-classes) vi-forms

  count-if : {A : Set} -> (A -> Bool) -> List A -> ℕ
  count-if f [] = 0
  count-if f (x ∷ xs) = if f x then suc (count-if f xs) else count-if f xs

  is-just? : Maybe SixCases -> Bool
  is-just? (just _) = true
  is-just? nothing = false

  is-pat? : SixCases -> Maybe SixCases -> Bool
  is-pat? p (just q) = p == q
  is-pat? p nothing = false

  target-line : String
  target-line =
    "0-descents found: " Str.++ show (count-if is-just? all-targets)
      Str.++ " of " Str.++ show (List.length all-targets)
      Str.++ " steps; by target pattern:"
      Str.++ List.foldr Str._++_ "" (List.map per-pat six-cases)
    where
      per-pat : SixCases -> String
      per-pat p = " " Str.++ show p Str.++ "=" Str.++ show (count-if (is-pat? p) all-targets)

  lemma-V-6-lines : List String
  lemma-V-6-lines =
      report-bool "the pattern classifier recognises the seven pattern matrices"
                  (all-b pat-self? six-cases)
    ∷ ("residue classes of a left generalized permutation: " Str.++ show (List.length left-classes))
    ∷ target-line
    ∷ report-bool "Lemma V.6: no K-count-1 0-descent from pattern (vi) reaches (ii) or (v)"
                  (all-b v6-ok vi-forms)
    ∷ []

-- ----------------------------------------------------------------------
-- * (D) The type-checked enumerations of Kopt.NormalForms
--
-- Kopt.NormalForms runs the residue-level enumerations of Lemmas V.3,
-- V.4 and V.6 at type-check time, using a cheap permutation invariant
-- of ℤ₂ patterns (the sums of the squares of the row and column
-- weights) in place of the orbit search pat-of-z2 above. Here we
-- re-evaluate those four checks at run time, and cross-check the two
-- classifiers against each other on exactly the matrices that Lemma
-- V.6 is about: whenever pat-of-z2 says a 0-descent target has pattern
-- p, its invariant is the one tabulated for p.

private
  agree-one : Matrix 4 4 R2 -> Tuple4 × (R2 × R2 × R2 × R2) -> Bool
  agree-one n lc = go (zero-descent-target (left-act (proj₁ lc) (proj₂ lc) n))
    where
      chk : Matrix 4 4 Z2 -> Maybe SixCases -> Bool
      chk z nothing = false
      chk z (just p) = NF.inv-eq (NF.inv z) (NF.pat-inv p)
      go : Maybe (Matrix 4 4 Z2) -> Bool
      go nothing = true
      go (just z) = chk z (pat-of-z2 z)

  classifiers-agree : Bool
  classifiers-agree = all-b (λ n -> all-b (agree-one n) left-classes) vi-forms

  normal-forms-lines : List String
  normal-forms-lines =
      report-bool "Kopt.NormalForms: the pattern invariant is constant on each orbit (7·576)"
                  NF.inv-perm-check
    ∷ report-bool "Kopt.NormalForms: Lemma V.3 over the six unitary normal forms" NF.v3-check
    ∷ report-bool "Kopt.NormalForms: Lemma V.4 over the 7·576·2 one-K-gate 1-ascents" NF.v4-check
    ∷ report-bool "Kopt.NormalForms: Lemma V.6 over the 4·384 residue steps" NF.v6-check
    ∷ report-bool "the invariant and the orbit search agree on every 0-descent target"
                  classifiers-agree
    ∷ []
-- ----------------------------------------------------------------------
-- * Main

private
  has-char : List Char -> Bool
  has-char [] = false
  has-char (_ ∷ _) = true

  nonempty : String -> Bool
  nonempty s = has-char (Str.toList s)

  path-of : List String -> String
  path-of (p ∷ _) = p
  path-of [] = "experiment_data.dat"

  sample-of : List String -> ℕ
  sample-of (_ ∷ n ∷ _) = nat-of-string n
  sample-of _ = 500

  run-file : String -> ℕ -> IO PU.⊤
  run-file content sample = do
    a <- loop 999 sample acc0 (List.filterᵇ nonempty (Str.lines content))
    putStrLn (Str.unlines (print-acc a))

  clifford-lines : List String
  clifford-lines =
      ("Clifford generalized permutations (K-count 0): " Str.++ show (KeySet.size (proj₁ level0)))
    ∷ ("Cliffords of K-count <= 1: " Str.++ show (KeySet.size (proj₁ level1)))
    ∷ ("Cliffords of K-count <= 2: " Str.++ show (KeySet.size (proj₁ level2)))
    ∷ report-bool "CliffordK2: that set is closed under all Clifford generators"
                  (closed? (proj₁ level2) (proj₂ level2))
    ∷ []

main : Main
main = run do
  args <- getArgs
  putStrLn "(A) the two-qubit Clifford group"
  putStrLn (Str.unlines clifford-lines)
  content <- readFiniteFile (path-of args)
  putStrLn "(B) the bounds of Section V on the authors' data set"
  run-file content (sample-of args)
  putStrLn "(C) Lemma V.6, over the residue normal forms"
  putStrLn (Str.unlines lemma-V-6-lines)
  putStrLn "(D) the type-checked enumerations of Kopt.NormalForms, re-run"
  putStrLn (Str.unlines normal-forms-lines)
