-- This module is an Agda port of the module Quantum.Synthesis.Clifford
-- of the Haskell package newsynth (by N. J. Ross and P. Selinger).
--
-- It provides an efficient symbolic representation of the Clifford
-- group on one qubit. This group is generated by S, H, and the scalar
-- ω = exp(iπ/4). It has 192 elements.
--
-- Differences from the Haskell version:
--
-- * The components of a Clifford operator are natural numbers
--   (Haskell: Int). Unlike Haskell, the constructor (Clifford') is
--   exported; it should only be applied to components in the ranges
--   documented at clifford-decompose (the lookup tables return 0s on
--   other inputs, where Haskell's are undefined).
--
-- * Haskell's ToClifford instance for Char raises an error on
--   characters other than "XYZHSEIWi-"; here such characters are
--   treated as the identity. Since String is not a list of
--   characters in Agda, there is an extra ToClifford instance for
--   String (as well as the generic one for lists).

{-# OPTIONS --without-K --safe #-}

module Quantum.Synthesis.Clifford where

open import Data.Bool.Base using (Bool ; true ; false ; if_then_else_ ; _∧_ ; _∨_)
open import Data.Char.Base using (Char)
open import Data.List.Base as List using (List ; [] ; _∷_)
open import Data.Nat.Base as Nat using (ℕ ; zero ; suc)
import Data.Nat.Show as NatS
open import Data.Product.Base using (_×_ ; _,_)
open import Data.String.Base as String using (String ; _++_)
open import Relation.Binary.PropositionalEquality using (_≡_ ; refl ; cong)
open import Relation.Nullary using (yes ; no)

open import Instances
open import Literals

-- ----------------------------------------------------------------------
-- * The Clifford group

-- A type representing single-qubit Clifford operators. The value
-- Clifford a b c d represents E^a X^b S^c ω^d, where a ∈ {0,1,2},
-- b ∈ {0,1}, c ∈ {0,…,3} and d ∈ {0,…,7}.
record Clifford : Set where
  constructor Clifford'
  field
    cl-a cl-b cl-c cl-d : ℕ


instance
  DecEqClifford : DecEq Clifford
  DecEqClifford ._≟_ (Clifford' a b c d) (Clifford' a' b' c' d') with a ≟ a' | b ≟ b' | c ≟ c' | d ≟ d'
  ... | yes refl | yes refl | yes refl | yes refl = yes refl
  ... | no p | _ | _ | _ = no λ { refl -> p refl }
  ... | yes _ | no p | _ | _ = no λ { refl -> p refl }
  ... | yes _ | yes _ | no p | _ = no λ { refl -> p refl }
  ... | yes _ | yes _ | yes _ | no p = no λ { refl -> p refl }

  -- The lexicographic order (Haskell: deriving Ord).
  DecOrdClifford : DecOrd Clifford
  DecOrdClifford = decOrd-from-bool le lt
    where
      lex : Clifford -> Clifford -> Bool -> Bool
      lex (Clifford' a b c d) (Clifford' a' b' c' d') eq =
        (a Nat.<ᵇ a') ∨ ((a Nat.≡ᵇ a') ∧ ((b Nat.<ᵇ b') ∨ ((b Nat.≡ᵇ b') ∧
        ((c Nat.<ᵇ c') ∨ ((c Nat.≡ᵇ c') ∧ ((d Nat.<ᵇ d') ∨ ((d Nat.≡ᵇ d') ∧ eq)))))))
      le lt : Clifford -> Clifford -> Bool
      le x y = lex x y true
      lt x y = lex x y false

  ShowClifford : Show Clifford
  ShowClifford .showsPrec _ (Clifford' a b c d) =
    "C" ++ NatS.show a ++ NatS.show b ++ NatS.show c ++ NatS.show d

-- ----------------------------------------------------------------------
-- ** Lookup tables

-- conj2 c b returns (c', d') such that S^c X^b = X^b S^c' ω^d'.
conj2 : ℕ -> ℕ -> ℕ × ℕ
conj2 0 0 = 0 , 0
conj2 0 1 = 0 , 0
conj2 1 0 = 1 , 0
conj2 1 1 = 3 , 2
conj2 2 0 = 2 , 0
conj2 2 1 = 2 , 4
conj2 3 0 = 3 , 0
conj2 3 1 = 1 , 6
conj2 _ _ = 0 , 0

-- conj3 b c a returns (a', b', c', d') such that
-- X^b S^c E^a = E^a' X^b' S^c' ω^d'.
conj3 : ℕ -> ℕ -> ℕ -> ℕ × ℕ × ℕ × ℕ
conj3 0 0 0 = 0 , 0 , 0 , 0
conj3 0 0 1 = 1 , 0 , 0 , 0
conj3 0 0 2 = 2 , 0 , 0 , 0
conj3 0 1 0 = 0 , 0 , 1 , 0
conj3 0 1 1 = 2 , 0 , 3 , 6
conj3 0 1 2 = 1 , 1 , 3 , 4
conj3 0 2 0 = 0 , 0 , 2 , 0
conj3 0 2 1 = 1 , 1 , 2 , 2
conj3 0 2 2 = 2 , 1 , 0 , 0
conj3 0 3 0 = 0 , 0 , 3 , 0
conj3 0 3 1 = 2 , 1 , 3 , 6
conj3 0 3 2 = 1 , 0 , 1 , 2
conj3 1 0 0 = 0 , 1 , 0 , 0
conj3 1 0 1 = 1 , 0 , 2 , 0
conj3 1 0 2 = 2 , 1 , 2 , 2
conj3 1 1 0 = 0 , 1 , 1 , 0
conj3 1 1 1 = 2 , 1 , 1 , 0
conj3 1 1 2 = 1 , 1 , 1 , 0
conj3 1 2 0 = 0 , 1 , 2 , 0
conj3 1 2 1 = 1 , 1 , 0 , 6
conj3 1 2 2 = 2 , 0 , 2 , 6
conj3 1 3 0 = 0 , 1 , 3 , 0
conj3 1 3 1 = 2 , 0 , 1 , 4
conj3 1 3 2 = 1 , 0 , 3 , 2
conj3 _ _ _ = 0 , 0 , 0 , 0

-- cinv a b c returns (a', b', c', d') such that
-- (E^a X^b S^c)⁻¹ = E^a' X^b' S^c' ω^d'.
cinv : ℕ -> ℕ -> ℕ -> ℕ × ℕ × ℕ × ℕ
cinv 0 0 0 = 0 , 0 , 0 , 0
cinv 0 0 1 = 0 , 0 , 3 , 0
cinv 0 0 2 = 0 , 0 , 2 , 0
cinv 0 0 3 = 0 , 0 , 1 , 0
cinv 0 1 0 = 0 , 1 , 0 , 0
cinv 0 1 1 = 0 , 1 , 1 , 6
cinv 0 1 2 = 0 , 1 , 2 , 4
cinv 0 1 3 = 0 , 1 , 3 , 2
cinv 1 0 0 = 2 , 0 , 0 , 0
cinv 1 0 1 = 1 , 0 , 1 , 2
cinv 1 0 2 = 2 , 1 , 0 , 0
cinv 1 0 3 = 1 , 1 , 3 , 4
cinv 1 1 0 = 2 , 1 , 2 , 2
cinv 1 1 1 = 1 , 1 , 1 , 6
cinv 1 1 2 = 2 , 0 , 2 , 2
cinv 1 1 3 = 1 , 0 , 3 , 4
cinv 2 0 0 = 1 , 0 , 0 , 0
cinv 2 0 1 = 2 , 1 , 3 , 6
cinv 2 0 2 = 1 , 1 , 2 , 2
cinv 2 0 3 = 2 , 0 , 3 , 6
cinv 2 1 0 = 1 , 0 , 2 , 0
cinv 2 1 1 = 2 , 1 , 1 , 6
cinv 2 1 2 = 1 , 1 , 0 , 2
cinv 2 1 3 = 2 , 0 , 1 , 6
cinv _ _ _ = 0 , 0 , 0 , 0

-- ----------------------------------------------------------------------
-- ** Axes

-- An axis is either I, H, or SH.
data Axis : Set where
  Axis-I Axis-H Axis-SH : Axis

instance
  DecEqAxis : DecEq Axis
  DecEqAxis ._≟_ Axis-I Axis-I = yes refl
  DecEqAxis ._≟_ Axis-I Axis-H = no λ ()
  DecEqAxis ._≟_ Axis-I Axis-SH = no λ ()
  DecEqAxis ._≟_ Axis-H Axis-I = no λ ()
  DecEqAxis ._≟_ Axis-H Axis-H = yes refl
  DecEqAxis ._≟_ Axis-H Axis-SH = no λ ()
  DecEqAxis ._≟_ Axis-SH Axis-I = no λ ()
  DecEqAxis ._≟_ Axis-SH Axis-H = no λ ()
  DecEqAxis ._≟_ Axis-SH Axis-SH = yes refl

  ShowAxis : Show Axis
  ShowAxis .showsPrec _ Axis-I = "Axis_I"
  ShowAxis .showsPrec _ Axis-H = "Axis_H"
  ShowAxis .showsPrec _ Axis-SH = "Axis_SH"

-- tconj a b returns (K, c, d) such that E^a X^b T = K T X^b S^c ω^d.
tconj : ℕ -> ℕ -> Axis × ℕ × ℕ
tconj 0 0 = Axis-I , 0 , 0
tconj 0 1 = Axis-I , 1 , 7
tconj 1 0 = Axis-H , 3 , 3
tconj 1 1 = Axis-H , 2 , 0
tconj 2 0 = Axis-SH , 0 , 5
tconj 2 1 = Axis-SH , 1 , 4
tconj _ _ = Axis-I , 0 , 0

-- ----------------------------------------------------------------------
-- ** Group operations

-- The identity Clifford operator.
clifford-id : Clifford
clifford-id = Clifford' 0 0 0 0

-- Clifford multiplication.
clifford-mult : Clifford -> Clifford -> Clifford
clifford-mult (Clifford' a1 b1 c1 d1) (Clifford' a2 b2 c2 d2) with conj3 b1 c1 a2
... | a3 , b3 , c3 , d3 with conj2 c3 b2
...   | c4 , d4 = Clifford' ((a1 + a3) % 3) ((b3 + b2) % 2) ((c4 + c2) % 4) ((d4 + d3 + d1 + d2) % 8)
  -- U = U1 U2
  --   = A1 B1 C1 D1 A2 B2 C2 D2
  --   = A1 (B1 C1 A2) B2 C2 D1 D2
  --   = A1 (A3 B3 C3 D3) B2 C2 D1 D2
  --   = A1 A3 B3 (C3 B2) C2 D3 D1 D2
  --   = A1 A3 B3 (B2 C4 D4) C2 D3 D1 D2
  --   = (A1 A3) (B3 B2) (C4 C2) (D4 D3 D1 D2)

-- ----------------------------------------------------------------------
-- ** Constructors

-- The Pauli X-gate as a Clifford operator.
clifford-X : Clifford
clifford-X = Clifford' 0 1 0 0

-- The Pauli Y-gate as a Clifford operator.
clifford-Y : Clifford
clifford-Y = Clifford' 0 1 2 2

-- The Pauli Z-gate as a Clifford operator.
clifford-Z : Clifford
clifford-Z = Clifford' 0 0 2 0

-- The Hadamard gate as a Clifford operator.
clifford-H : Clifford
clifford-H = Clifford' 1 0 1 5

-- The Clifford operator S.
clifford-S : Clifford
clifford-S = Clifford' 0 0 1 0

-- The Clifford operator SH.
clifford-SH : Clifford
clifford-SH = clifford-mult clifford-S clifford-H

-- The Clifford operator E = H S³ ω³. This operator is uniquely
-- determined by the properties E³ = I, EXE⁻¹ = Y, EYE⁻¹ = Z, and
-- EZE⁻¹ = X.
clifford-E : Clifford
clifford-E = Clifford' 1 0 0 0

-- The Clifford operator ω = exp(iπ/4).
clifford-W : Clifford
clifford-W = Clifford' 0 0 0 1

-- A type class for things that can be exactly converted to a
-- Clifford operator. One particular instance of this is String, so
-- that Clifford operators can be denoted, e.g., to-clifford "-iX".
-- The valid characters for such string conversions are "XYZHSEIWi-".
record ToClifford (A : Set) : Set where
  field
    -- Convert any suitable thing to a Clifford operator.
    to-clifford : A -> Clifford
open ToClifford {{...}} public

instance
  ToCliffordClifford : ToClifford Clifford
  ToCliffordClifford .to-clifford x = x

  -- Unknown characters are mapped to the identity (Haskell: error).
  ToCliffordChar : ToClifford Char
  ToCliffordChar .to-clifford 'E' = clifford-E
  ToCliffordChar .to-clifford 'X' = clifford-X
  ToCliffordChar .to-clifford 'S' = clifford-S
  ToCliffordChar .to-clifford 'W' = clifford-W
  ToCliffordChar .to-clifford 'I' = clifford-id
  ToCliffordChar .to-clifford 'i' = Clifford' 0 0 0 2
  ToCliffordChar .to-clifford '-' = Clifford' 0 0 0 4
  ToCliffordChar .to-clifford 'H' = clifford-H
  ToCliffordChar .to-clifford 'Y' = clifford-Y
  ToCliffordChar .to-clifford 'Z' = clifford-Z
  ToCliffordChar .to-clifford _ = clifford-id

  ToCliffordList : {A : Set} {{_ : ToClifford A}} -> ToClifford (List A)
  ToCliffordList {A} .to-clifford = go
    where
      go : List A -> Clifford
      go [] = clifford-id
      go (h ∷ t) = clifford-mult (to-clifford h) (go t)

  ToCliffordString : ToClifford String
  ToCliffordString .to-clifford s = to-clifford (String.toList s)

-- ----------------------------------------------------------------------
-- ** Deconstructors

-- Given a Clifford operator U, return (a, b, c, d) such that
--
-- * U = E^a X^b S^c ω^d,
-- * a ∈ {0, 1, 2}, b ∈ {0, 1}, c ∈ {0, …, 3}, and d ∈ {0, …, 7}.
--
-- Here, E = H S³ ω³. Note that E, X, S, and ω have order 3, 2, 4, and
-- 8, respectively. Moreover, each Clifford operator can be uniquely
-- represented as above.
clifford-decompose : {A : Set} {{_ : ToClifford A}} -> A -> ℕ × ℕ × ℕ × ℕ
clifford-decompose m with to-clifford m
... | Clifford' a b c d = a , b , c , d

-- Clifford inverse.
clifford-inv : {A : Set} {{_ : ToClifford A}} -> A -> Clifford
clifford-inv op with to-clifford op
... | Clifford' a b c d with cinv a b c
...   | a2 , b2 , c2 , d2 = Clifford' a2 b2 c2 ((d2 + 8 Nat.∸ d) % 8)
  -- U⁻¹ = (A B C)⁻¹ D⁻¹ = (A2 B2 C2 D2) D⁻¹

private
  -- The Clifford operators of the axes, and the inverses of H and SH,
  -- as top-level constants (they are computed only once in compiled
  -- code, instead of parsing the strings at every use).
  clifford-axis-I clifford-axis-H clifford-axis-SH clifford-inv-H clifford-inv-SH : Clifford
  clifford-axis-I = to-clifford "I"
  clifford-axis-H = to-clifford "H"
  clifford-axis-SH = to-clifford "SH"
  clifford-inv-H = clifford-inv "H"
  clifford-inv-SH = clifford-inv "SH"

instance
  ToCliffordAxis : ToClifford Axis
  ToCliffordAxis .to-clifford Axis-I = clifford-axis-I
  ToCliffordAxis .to-clifford Axis-H = clifford-axis-H
  ToCliffordAxis .to-clifford Axis-SH = clifford-axis-SH

-- Given a Clifford operator U, return (K, b, c, d) such that
--
-- * U = K X^b S^c ω^d,
-- * K ∈ {I, H, SH}, b ∈ {0, 1}, c ∈ {0, …, 3}, and d ∈ {0, …, 7}.
clifford-decompose-coset : {A : Set} {{_ : ToClifford A}} -> A -> Axis × ℕ × ℕ × ℕ
clifford-decompose-coset u = aux (to-clifford u)
  where
    rest : Axis -> Clifford -> Axis × ℕ × ℕ × ℕ
    rest k (Clifford' _ b c d) = k , b , c , d

    aux : Clifford -> Axis × ℕ × ℕ × ℕ
    aux op@(Clifford' 0 _ _ _) = rest Axis-I op
    aux op@(Clifford' 1 _ _ _) = rest Axis-H (clifford-mult clifford-inv-H op)
    aux op = rest Axis-SH (clifford-mult clifford-inv-SH op)

-- ----------------------------------------------------------------------
-- ** Conjugation by T

-- Given a Clifford gate C, return an axis K ∈ {I, H, SH} and a
-- Clifford gate C' such that
--
-- * C T = K T C'.
clifford-tconj : Clifford -> Axis × Clifford
clifford-tconj (Clifford' a1 b1 c1 d1) with tconj a1 b1
... | k , c2 , d2 = k , Clifford' 0 b1 ((c2 + c1) % 4) ((d2 + d1) % 8)
  -- U T = A1 B1 C1 D1 T
  --     = (A1 B1 T) C1 D1
  --     = (K T B1 C2 D2) C1 D1
  --     = K T B1 (C2 C1) (D2 D1)
